import { db } from '@/db';
import { irlSessions } from '@/db/schema';

async function main() {
    const sampleSessions = [
        {
            type: 'presentiel',
            domain: 'Développement web/logiciel',
            location: 'Coworking Spaces Paris - Le Marais, 15 Rue du Temple, 75004 Paris',
            date: '2025-01-15',
            time: '14:00',
            duration: '2h',
            level: 'Débutant',
            objective: 'Apprendre les bases de React et créer sa première application interactive avec les hooks et composants fonctionnels',
            timezone: null,
            videoLink: null,
            status: 'upcoming',
            organizerName: 'Sophie Dubois',
            maxParticipants: 6,
            message: 'Apportez votre ordinateur portable avec Node.js installé',
            createdAt: new Date('2024-12-10').toISOString(),
        },
        {
            type: 'distanciel',
            domain: 'Développement web/logiciel',
            location: null,
            date: '2025-01-16',
            time: '10:00',
            duration: '1h30',
            level: 'Intermédiaire',
            objective: 'Maîtriser les techniques avancées de TypeScript : generics, types utilitaires et conditional types',
            timezone: 'Europe/Paris',
            videoLink: 'https://meet.google.com/abc-defg-hij',
            status: 'upcoming',
            organizerName: 'Pierre Martin',
            maxParticipants: 8,
            message: null,
            createdAt: new Date('2024-12-12').toISOString(),
        },
        {
            type: 'presentiel',
            domain: 'Cybersécurité',
            location: 'Médiathèque de Lyon Part-Dieu, 30 Boulevard Vivier Merle, 69003 Lyon',
            date: '2025-01-18',
            time: '15:30',
            duration: '1h30',
            level: 'Débutant',
            objective: 'Comprendre les attaques XSS et CSRF : démonstration pratique et méthodes de protection pour sécuriser vos applications web',
            timezone: null,
            videoLink: null,
            status: 'upcoming',
            organizerName: 'Thomas Leroy',
            maxParticipants: 5,
            message: 'Session pratique avec des exercices en live',
            createdAt: new Date('2024-12-15').toISOString(),
        },
        {
            type: 'distanciel',
            domain: 'Cybersécurité',
            location: null,
            date: '2025-01-20',
            time: '18:00',
            duration: '1h',
            level: 'Avancé',
            objective: 'Pentesting avancé : exploiter les vulnérabilités SQL injection et effectuer des tests d\'intrusion éthiques',
            timezone: 'UTC',
            videoLink: 'https://zoom.us/j/1234567890',
            status: 'upcoming',
            organizerName: 'Marie Dupont',
            maxParticipants: 4,
            message: 'Pré-requis : connaissances en bases de données et sécurité web',
            createdAt: new Date('2024-12-18').toISOString(),
        },
        {
            type: 'presentiel',
            domain: 'Développement IA/ML',
            location: 'Coworking La Cantine Toulouse, 27 Rue d\'Aubuisson, 31000 Toulouse',
            date: '2025-01-22',
            time: '09:30',
            duration: '2h',
            level: 'Intermédiaire',
            objective: 'Créer son premier modèle de machine learning avec Python et scikit-learn : régression linéaire et classification',
            timezone: null,
            videoLink: null,
            status: 'completed',
            organizerName: 'Lucas Bernard',
            maxParticipants: 6,
            message: null,
            createdAt: new Date('2024-12-05').toISOString(),
        },
        {
            type: 'distanciel',
            domain: 'Développement IA/ML',
            location: null,
            date: '2025-01-23',
            time: '16:00',
            duration: '45min',
            level: 'Débutant',
            objective: 'Introduction aux réseaux de neurones : comprendre le perceptron et les bases du deep learning',
            timezone: 'Europe/Paris',
            videoLink: 'https://teams.microsoft.com/l/meetup-join/xyz123',
            status: 'upcoming',
            organizerName: 'Emma Rousseau',
            maxParticipants: 8,
            message: 'Aucun prérequis technique nécessaire, session accessible à tous',
            createdAt: new Date('2024-12-20').toISOString(),
        },
        {
            type: 'presentiel',
            domain: 'Développement web/logiciel',
            location: 'Médiathèque Mériadeck, 85 Cours du Maréchal Juin, 33000 Bordeaux',
            date: '2025-01-25',
            time: '11:00',
            duration: '1h',
            level: 'Avancé',
            objective: 'Architectures microservices avec Node.js : patterns, communication inter-services et déploiement Docker',
            timezone: null,
            videoLink: null,
            status: 'upcoming',
            organizerName: 'Antoine Moreau',
            maxParticipants: 5,
            message: 'Expérience en développement backend requise',
            createdAt: new Date('2024-12-22').toISOString(),
        },
        {
            type: 'distanciel',
            domain: 'Cybersécurité',
            location: null,
            date: '2025-01-26',
            time: '14:30',
            duration: '30min',
            level: 'Intermédiaire',
            objective: 'Sécuriser ses API REST : authentification JWT, CORS et bonnes pratiques de validation des données',
            timezone: 'America/New_York',
            videoLink: 'https://meet.google.com/sec-api-rest',
            status: 'cancelled',
            organizerName: 'Camille Laurent',
            maxParticipants: 6,
            message: 'Session annulée - reportée au mois prochain',
            createdAt: new Date('2024-12-08').toISOString(),
        },
        {
            type: 'presentiel',
            domain: 'Cybersécurité',
            location: 'La Paillasse Paris, 226 Rue Saint-Denis, 75002 Paris',
            date: '2025-01-28',
            time: '17:00',
            duration: '1h30',
            level: 'Avancé',
            objective: 'Cryptographie moderne : algorithmes de chiffrement symétrique et asymétrique, certificats SSL/TLS',
            timezone: null,
            videoLink: null,
            status: 'upcoming',
            organizerName: 'Julien Petit',
            maxParticipants: 4,
            message: null,
            createdAt: new Date('2024-12-25').toISOString(),
        },
        {
            type: 'distanciel',
            domain: 'Développement IA/ML',
            location: null,
            date: '2025-01-29',
            time: '13:00',
            duration: '2h',
            level: 'Avancé',
            objective: 'Déployer des modèles ML en production : optimisation, monitoring et MLOps avec TensorFlow Serving',
            timezone: 'Europe/Paris',
            videoLink: 'https://zoom.us/j/mlops-prod-2025',
            status: 'upcoming',
            organizerName: 'Sarah Cohen',
            maxParticipants: 5,
            message: 'Connaissances avancées en ML et DevOps requises',
            createdAt: new Date('2024-12-28').toISOString(),
        },
        {
            type: 'presentiel',
            domain: 'Développement IA/ML',
            location: 'Coworking Mutinerie Village, 29 Rue de Meaux, 75019 Paris',
            date: '2025-01-30',
            time: '10:30',
            duration: '1h',
            level: 'Débutant',
            objective: 'Traitement du langage naturel (NLP) : créer un chatbot simple avec Python et les transformers',
            timezone: null,
            videoLink: null,
            status: 'completed',
            organizerName: 'Nicolas Fournier',
            maxParticipants: 7,
            message: 'Ordinateur portable requis avec Python 3.8+ installé',
            createdAt: new Date('2024-12-02').toISOString(),
        },
        {
            type: 'distanciel',
            domain: 'Développement web/logiciel',
            location: null,
            date: '2025-01-31',
            time: '19:00',
            duration: '45min',
            level: 'Intermédiaire',
            objective: 'Optimisation des performances web : lazy loading, code splitting et techniques de mise en cache avancées',
            timezone: 'UTC',
            videoLink: 'https://teams.microsoft.com/l/meetup-join/perf-web',
            status: 'upcoming',
            organizerName: 'Léa Garnier',
            maxParticipants: 8,
            message: null,
            createdAt: new Date('2024-12-30').toISOString(),
        },
    ];

    await db.insert(irlSessions).values(sampleSessions);
    
    console.log('✅ IRL Sessions seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});