import { db } from '@/db';
import { user, profiles } from '@/db/schema';

async function main() {
    // First, create sample users
    const sampleUsers = [
        {
            id: 'user_1',
            name: 'Marie Dubois',
            email: 'marie.dubois@example.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-06-15'),
            updatedAt: new Date('2024-06-15'),
        },
        {
            id: 'user_2',
            name: 'Pierre Martin',
            email: 'pierre.martin@example.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-07-01'),
            updatedAt: new Date('2024-07-01'),
        },
        {
            id: 'user_3',
            name: 'Sophie Laurent',
            email: 'sophie.laurent@example.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-07-15'),
            updatedAt: new Date('2024-07-15'),
        },
        {
            id: 'user_4',
            name: 'Thomas Bernard',
            email: 'thomas.bernard@example.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-08-01'),
            updatedAt: new Date('2024-08-01'),
        },
        {
            id: 'user_5',
            name: 'Julie Petit',
            email: 'julie.petit@example.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-08-15'),
            updatedAt: new Date('2024-08-15'),
        },
        {
            id: 'user_6',
            name: 'Lucas Moreau',
            email: 'lucas.moreau@example.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-09-01'),
            updatedAt: new Date('2024-09-01'),
        },
        {
            id: 'user_7',
            name: 'Emma Rousseau',
            email: 'emma.rousseau@example.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-09-15'),
            updatedAt: new Date('2024-09-15'),
        },
        {
            id: 'user_8',
            name: 'Alexandre Garcia',
            email: 'alexandre.garcia@example.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-10-01'),
            updatedAt: new Date('2024-10-01'),
        },
        {
            id: 'user_9',
            name: 'Léa Simon',
            email: 'lea.simon@example.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-10-15'),
            updatedAt: new Date('2024-10-15'),
        },
        {
            id: 'user_10',
            name: 'Hugo Lefevre',
            email: 'hugo.lefevre@example.com',
            emailVerified: true,
            image: null,
            createdAt: new Date('2024-11-01'),
            updatedAt: new Date('2024-11-01'),
        },
    ];

    await db.insert(user).values(sampleUsers);

    // Now create corresponding profiles
    const sampleProfiles = [
        {
            userId: 'user_1',
            username: 'marie.dev',
            avatarUrl: 'https://avatar.example.com/user1.jpg',
            bio: 'Passionnée par le développement web fullstack. J\'adore React et Node.js. Toujours prête à apprendre de nouvelles technologies.',
            domaines: JSON.stringify(['Développement web/logiciel']),
            niveau: 'Intermédiaire',
            visibility: 'public',
            xp: 2500,
            level: 8,
            createdAt: new Date('2024-06-15').toISOString(),
            updatedAt: new Date('2024-06-16').toISOString(),
        },
        {
            userId: 'user_2',
            username: 'pierre_cyber',
            avatarUrl: null,
            bio: 'Expert en cybersécurité et tests de pénétration. Formation en sécurité des réseaux et cryptographie.',
            domaines: JSON.stringify(['Cybersécurité']),
            niveau: 'Avancé',
            visibility: 'public',
            xp: 4200,
            level: 12,
            createdAt: new Date('2024-07-01').toISOString(),
            updatedAt: new Date('2024-07-01').toISOString(),
        },
        {
            userId: 'user_3',
            username: 'sophie-ai',
            avatarUrl: 'https://avatar.example.com/user3.jpg',
            bio: 'Chercheure en intelligence artificielle et machine learning. Spécialisée dans le deep learning et les réseaux de neurones.',
            domaines: JSON.stringify(['Développement IA/ML']),
            niveau: 'Expert',
            visibility: 'public',
            xp: 5000,
            level: 15,
            createdAt: new Date('2024-07-15').toISOString(),
            updatedAt: new Date('2024-07-20').toISOString(),
        },
        {
            userId: 'user_4',
            username: 'thomas.ml',
            avatarUrl: 'https://avatar.example.com/user4.jpg',
            bio: null,
            domaines: JSON.stringify(['Développement IA/ML', 'Développement web/logiciel']),
            niveau: 'Intermédiaire',
            visibility: 'public',
            xp: 1800,
            level: 6,
            createdAt: new Date('2024-08-01').toISOString(),
            updatedAt: new Date('2024-08-01').toISOString(),
        },
        {
            userId: 'user_5',
            username: 'julie_web',
            avatarUrl: null,
            bio: 'Développeuse frontend spécialisée en design systems et accessibilité web. Fan de CSS et animations.',
            domaines: JSON.stringify(['Développement web/logiciel']),
            niveau: 'Intermédiaire',
            visibility: 'private',
            xp: 2100,
            level: 7,
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-16').toISOString(),
        },
        {
            userId: 'user_6',
            username: 'lucas-sec',
            avatarUrl: 'https://avatar.example.com/user6.jpg',
            bio: 'Analyste en sécurité informatique. Je me concentre sur la détection des vulnérabilités et la réponse aux incidents.',
            domaines: JSON.stringify(['Cybersécurité', 'Développement web/logiciel']),
            niveau: 'Avancé',
            visibility: 'public',
            xp: 3800,
            level: 11,
            createdAt: new Date('2024-09-01').toISOString(),
            updatedAt: new Date('2024-09-05').toISOString(),
        },
        {
            userId: 'user_7',
            username: 'emma.code',
            avatarUrl: 'https://avatar.example.com/user7.jpg',
            bio: 'Développeuse backend Python passionnée par les architectures microservices et le cloud computing.',
            domaines: JSON.stringify(['Développement web/logiciel']),
            niveau: 'Intermédiaire',
            visibility: 'public',
            xp: 1500,
            level: 5,
            createdAt: new Date('2024-09-15').toISOString(),
            updatedAt: new Date('2024-09-15').toISOString(),
        },
        {
            userId: 'user_8',
            username: 'alex_data',
            avatarUrl: null,
            bio: null,
            domaines: JSON.stringify(['Développement IA/ML']),
            niveau: 'Débutant',
            visibility: 'public',
            xp: 500,
            level: 2,
            createdAt: new Date('2024-10-01').toISOString(),
            updatedAt: new Date('2024-10-01').toISOString(),
        },
        {
            userId: 'user_9',
            username: 'lea.security',
            avatarUrl: 'https://avatar.example.com/user9.jpg',
            bio: 'Passionnée par la cybersécurité et l\'ethical hacking. En formation continue sur les dernières menaces et protections.',
            domaines: JSON.stringify(['Cybersécurité']),
            niveau: 'Débutant',
            visibility: 'private',
            xp: 300,
            level: 1,
            createdAt: new Date('2024-10-15').toISOString(),
            updatedAt: new Date('2024-10-16').toISOString(),
        },
        {
            userId: 'user_10',
            username: 'hugo_fullstack',
            avatarUrl: 'https://avatar.example.com/user10.jpg',
            bio: 'Développeur fullstack JavaScript/TypeScript. Expérience avec React, Next.js, Node.js et bases de données SQL/NoSQL.',
            domaines: JSON.stringify(['Développement web/logiciel', 'Développement IA/ML']),
            niveau: 'Débutant',
            visibility: 'public',
            xp: 800,
            level: 3,
            createdAt: new Date('2024-11-01').toISOString(),
            updatedAt: new Date('2024-11-02').toISOString(),
        },
    ];

    await db.insert(profiles).values(sampleProfiles);
    
    console.log('✅ Profiles seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});